#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     hfgh,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flagspin,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    scoopL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    winch,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    turret,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_4,    scoopR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int i;
int servoPower;
int maxPower = 255;
int minPower = -255;
int stopPower = -1;
//variables for the drivetrain
float rpower;
float lpower;
int deadzone = 10;   //for joysticks
int slowpower = 30.0;  //used on tophat for minor adjustments

//variables for the turret
int turretTarget; // where the turret will end up
int turretMax = 60;
int turretMin = 12;

//varibles for the scoop
int offset = -6;
int RscoopTarget;
int LscoopTarget;

//variables for motor stall check
#define bshooterStalled()   (nStallCount > 3)
int nStallCount = 0;

//variables for the shooter
int shooterPower;

void initializeRobot()
{
	//RscoopTarget = 20;
	//LscoopTarget = 	255 - RscoopTarget + offset;
	//servo[scoopL] = RscoopTarget;
	//servo[scoopR] = LscoopTarget;
	servo[turret] = 10;
	shooterPower = 70;
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

///////////////////////////////////////////////////////////////////////////////////////////////////////
////                                                                                                 //
////                                        Shooter                                                  //
////                                                                                                 //
///////////////////////////////////////////////////////////////////////////////////////////////////////
////
//void shoot()
//{
//	if (joy2Btn(3))  //when button b is pressed
//	{
//		motor[shooter] = shooterPower;
//		wait10Msec(100);
//		//while(nMotorEncoder[shooter] < 4000)
//		//{
//		//	motor[shooter] = shooterPower;  //block is fired
//		//}
//		motor[shooter] = 0;
//	}
//	else if(joy2Btn(8))
//	{
//		motor[shooter] = -30;
//	}
//	else if(joystick.joy2_TopHat == 0 && shooterPower < 100) //if up arrow is pressed
//	{
//		shooterPower = shooterPower + 10; //shoot further
//		wait10Msec(80);
//	}
//	else if(joystick.joy2_TopHat == 4 && shooterPower >= 0) //if down arrow is pressed
//	{
//		shooterPower = shooterPower - 10; //shorten range
//		wait10Msec(80);
//	}
//	else
//	{
//		motor[shooter] = 0;
//	}
//}

//void rollback()
//{
//	if (joy2Btn(6)) //if the top right trigger is pressed
//	{
//		motor[shooter] = -10; //motor starts going backwards
//		if (bshooterStalled())  //when the motor stalls
//    {
//      motor[shooter] = 0; //the motor stops
//    }
//  }
//}
//void flag()
//{
//	int flagPower = 20;
//	if (joy2Btn(5))   //if top L trigger is pressed spins flag up
//	{
//		motor[flagspin]= flagPower; //sets motor to flagPower
//		if (flagPower <= 100) //limits motorPower to 100
//		{
//			flagPower = flagPower + 1; //gradually increases flagPower so we dont rip the handle off
//			wait1Msec(25);
//		}
//	}
//	else if (joy2Btn(7)) //if bottom L trigger flag down
//	{
//		motor[flagspin] = -60; //spins flag down slowerly
//	}
//	else
//	{
//		motor [flagspin] = 0; //if no buttons are pressed the motor stops
//	}
//}

void spin()
{
	while(joystick.joy2_TopHat == 6) //left tophat moves turret to the right
	{
		if(turretTarget < turretMax) //sets limit on how far left the turret can go
		{
			turretTarget = turretTarget + 2; //adds to turretTarget making it move left
			wait10Msec(10);
			servo[turret] = turretTarget; //moves to target
		}
	}
	while(joystick.joy2_TopHat == 2)  // right tophat moves turret to the left
	{
		if(turretTarget > turretMin) //sets a limit on the right side of robot
		{
			turretTarget = turretTarget - 2; //subtracts form turretTarget moving it right
			wait10Msec(10);
			servo[turret] = turretTarget; //moves to target
		}
	}
}



task main()
{
	initializeRobot();
	while(true)
	{
		eraseDisplay();
		nxtDisplayCenteredBigTextLine(3, "%d", shooterPower);
		getJoystickSettings(joystick);
		spin();
	}
}
