#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Servo,  srvo_S1_C1_1,    buckettest,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    buckettest2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int i;

task main()
{
	servo[buckettest] = 255;
	servo[buckettest2] = 255;
	while(true)
	{
		if(nNxtButtonPressed == 1)
		{
			servo[buckettest] = 100;
			servo[buckettest2] = 100;
		}
		if(nNxtButtonPressed == 2)
		{
			servo[buckettest] = 250;
			servo[buckettest2] = 250;
		}
	}
	//servo[buckettest] = 0;
	//while(true)
 // {
 //   if(nNxtButtonPressed == 1)
 //   {
 //   	i = i + 10;
 //   	wait10Msec(10);
 //   	servo[buckettest] = i;
 //   	servo[buckettest2] = i;
 //   }
 //   if (nNxtButtonPressed == 2)
 //   {
 //   	i = i - 10;
 //   	wait10Msec(10);
 //   	servo[buckettest] = i;
 //   	servo[buckettest2] = i;
 //   }
  //}
}
