#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rdrive,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ldrive,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     kicker,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flagspin,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     wench1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     wench2,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    autoblock,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    irservo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    wedgel,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    wedger,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    sabotage,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    linney,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

//variables
float rpower;
float lpower;
int deadzone = 10;   //for joysticks
int slowpower = 60.0;  //used on tophat for minor adjustments

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                        Tank Drive                                               //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void TankDrive(int topHat, int y1, int y2)
{
	rpower = (y2 / 128.0) * 100; // rpower Proportional to right analog stick's Y-axis value
  lpower = (y1 / 128.0) * 100; // lpower proportional to left analog stick's Y-axis value
  if (abs(lpower) < deadzone)
  {
  	lpower = 0;  // Left side deadzone
  }
  if (abs(rpower) < deadzone)
  {
	  rpower = 0;  // Right side deadzone
	}
  	motor[rdrive] = rpower;      //|Set power to motors
  	motor[ldrive] = lpower;      //|
}	// end TankDrive

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                       Wench/Lift                                                //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void Wenches ()
{
	if (joy1Btn(5))
	{
		motor[wench1] = 30;    // spins spools towards front of bot
		motor[wench2] = 30;
	}
	else if (joy1Btn(7))
	{
		motor[wench1] = -30;   //spins spools towards back of bot
		motor[wench2] = -30;
	}
	else
	{
		motor[wench1] = 0;   //sets default to stop it
		motor[wench2] = 0;
	}
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                   Block Kicker/Wedge                                            //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void BlockKicker()
{
	if(joy1Btn(6))
	{
		motor[kicker] = 100;
	}
	else if(joy1Btn(8))
	{
		motor[kicker] = -100;
	}
	else
	{
		motor[kicker] = 0;
	}
}

void kicklinney()
{
	if(joystick.joy1_TopHat == 0)
	{
		servo[linney] = 255;
	}
	else if(joystick.joy1_TopHat == 4)
	{
		servo[linney] = 0;
	}
	else
	{
		servo[linney] = 127;
	}
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                      Flag Spinner                                               //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////
void FlagSpinner()
{
	if (joy1Btn(1))
	{
		motor[flagspin]= 100;
	}
	else if (joy1Btn(2))
	{
		motor[flagspin]=-50;
	}
	else
	{
		motor [flagspin] = 0;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                      IRservo                                                    //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                      AutoBlock                                                  //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////
void AutonomousBlock()
{
	if (joy1Btn(3))
	{
		servo[autoblock] = 255;
	}
	else if(joy1Btn(2))
	{
		servo[autoblock] = 50;
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
  	getJoystickSettings(joystick);
  	TankDrive(joystick.joy1_TopHat, joystick.joy1_y1, joystick.joy1_y2);
  	Wenches();
  	BlockKicker();
  	kicklinney();
  	FlagSpinner();
  	AutonomousBlock();
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
  }
}
