#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS,          sensorI2CCustom)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LBDrive,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RBDrive,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     shoulder,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     wrist,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     LFDrive,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     RFDrive,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    lateral,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    bayonet,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    IRservo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!! *//

#include "JoystickDriver.c"            //Include file to "handle" the Bluetooth messages.
#include "hitechnic-touchmux.h"        //include file for the touch sensor mux
#include "hitechnic-gyro.h"            //include for the gyro
#include "hitechnic-sensormux.h"       //SMUX driver
#include "lego-ultrasound.h"           //for sonar sensor
#include "hitechnic-irseeker-v2.h"     //for IR seeker sensor
#include "lego-touch.h"                //for touch sensor
//#include "RingItUp_Bot2_Includes.c"    //include files

//variables
float rpower;
float lpower;
int deadzone = 10;
int slowpower = 60.0;
int wristpower = 40;

void initializeRobot()
{
	nNoMessageCounterLimit = 200;
  servo[bayonet] = 240;                //sets bayonet inside the hand
	servo[IRservo] = 117;                //sets IRseeker in position to make decisions
	nMotorEncoder[wrist] = 0;            //zeros wrist encoder
	//HTEOPDsetLongRange(HTEOPD);          //sets EOPD to long range instead of short range
	servo[lateral] = 127;
	return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                 //
//                                        Tank Drive                                               //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void TankDrive(int topHat, int y1, int y2)
{
	rpower = (y2 / 128.0) * 100; // rpower Proportional to right analog stick's Y-axis value
  lpower = (y1 / 128.0) * 100; // lpower proportional to left analog stick's Y-axis value
  if (abs(lpower) < deadzone)
  {
  	lpower = 0;  // Left side deadzone
	}
  if (abs(rpower) < deadzone)
  {
	  rpower = 0;  // Right side deadzone
	}
  motor[RBDrive] = rpower;      //|
  motor[RFDrive] = rpower;      //| Set power to motors
  motor[LBDrive] = lpower;      //|
  motor[LFDrive] = lpower;      //|
}	// end TankDrive

/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                    Shoulder                                                     //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void ManipulatorShoulder ()
{
	if (joy1Btn(6))
	{
		motor[shoulder] = 100;
	}
	if (joy1Btn(8))
	{
		motor[shoulder] = 100;
	}
	if (TSreadState(msensor_S3_4)) //upper limit
	{
		motor[shoulder] =  0;   //move    positive numbers go up
	}
	else if (TSreadState(msensor_S3_3)) // lower limit
	{
		motor[shoulder] =  0;   //move    positive numbers go up
	}
}
/////////////////////////////////////////////////////////////////////////////////////////////////////
//                                   Manipulator Wrist                                             //
//                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////

void ManipulatorWrist()
{
	if(joystick.joy1_TopHat == 4 /*&& nMotorEncoder[wrist] > 0/*&& wristposition > 87*/)   //bring hand down
	{
		motor[wrist] = wristpower;      //Get ring, pick up ring, flip flipper down
		//wristposition = nMotorEncoder[wrist];
	}
	else if (joystick.joy1_TopHat == 0 /*&& nMotorEncoder[wrist] < 1150/*&& wristposition < 240*/) //bring hand up
	{
		motor[wrist] = -wristpower;    //release ring, bring flipper up
		//wristposition = nMotorEncoder[wrist];
	}
	else
	{
		motor[wrist] = 0;
	}
}

void Linney()
{
	if (joystick.joy1_TopHat == 2) //right dpad moves linney right
	{
		servo[lateral] = 255;
	}
	else if (joystick.joy1_TopHat ==6) //left dpad moves linney left
	{
		servo[lateral] = 0;
	}
	else
	{
		servo[lateral] = 127; //else do NOTHING!
	}
}

void WristBayonet()
{
	if (joy1Btn(5))
	{
		servo[bayonet] = 145; //close bayonet
	}
	else if (joy1Btn(7))
	{
		servo[bayonet] = 235; //open bayonet
	}
}

task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase
  while (true)
  {
  	getJoystickSettings(joystick);
  	TankDrive(joystick.joy1_y1, joystick.joy1_y2);
  	ManipulatorShoulder();
  	//ManipulatorWrist();  //COMMENT OUT TO CHILDPROOF
  	//Linney();            //COMMENT OUT TO CHILDPROOF
  	WristBayonet();
  	backup();
  }
}
