#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rdrive,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ldrive,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C2_1,     flagspin,      tmotorTetrix, openLoop, reversed)
//#pragma config(Motor,  mtr_S1_C2_2,     shooter,       tmotorTetrix, openLoop, reversed)
//#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//#pragma config(Servo,  srvo_S2_C1_1,    turret,               tServoContinuousRotation)
//#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
//#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
//#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
//#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
//#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//#pragma config(Servo,  srvo_S2_C2_1,    scoopR,               tServoStandard)
//#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
//#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
//#pragma config(Servo,  srvo_S2_C2_4,    scoopL,               tServoStandard)
//#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
//#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "BlockPartyIncludes.c"

const tMUXSensor HTIRS2 = msensor_S4_1;

int _dirAC;
//int count = 0;
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	//servo[scoopL] = 0;
	//servo[scoopR] = 255;

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  //initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.

  //servo[scoopL] = 245;
  //servo[scoopR] = 10;
	straight(100, 100, 18);
	wait10Msec(10);
	_dirAC = HTIRS2readACDir(HTIRS2);      //read IR seeker value
	if(_dirAC > 5)
	{
		//insert code to dump block
		motor[rdrive] = 0;
		motor[ldrive] = 0;
		wait10Msec(30000); //for testing only, remove when block dump is added  THIS IS FOR ALL WAIT(3000000)!!!!
		straight(100,100, 45);  //change the 5 to whatever distance fit the situation
		GyroLeft(45, 100000000);
		straight(100, 100, 39);
		GyroRight(47, 10000000);
		MBD(42, 100, 1000000);
	}
	else
	{
		straight(100, 100, 12);
	  _dirAC = HTIRS2readACDir(HTIRS2);      //read IR seeker value
		if(_dirAC > 5)
		{
			//insert dump block code
			motor[rdrive] = 0;
			motor[ldrive] = 0;
			wait10Msec(30000);
			//straight(100,100, 5);  //change the 5 to whatever distance fit the situation
			//GyroLeft(45, 100000000);
			//straight(100, 100, 39);
			//GyroRight(47, 10000000);
			//MBD(42, 100, 1000000);
		}
		else
		{
			straight(100, 100, 22);
			 _dirAC = HTIRS2readACDir(HTIRS2);      //read IR seeker value
			if(_dirAC > 5)
			{
				//dump blcok
				motor[rdrive] = 0;
				motor[ldrive] = 0;
				wait10Msec(30000);
				//straight(100,100, 5);  //change the 5 to whatever distance fit the situation
				//GyroLeft(45, 100000000);
				//straight(100, 100, 39);
				//GyroRight(47, 10000000);
				//MBD(42, 100, 1000000);
			}
			else
			{
				straight(100, 100, 10);
			  _dirAC = HTIRS2readACDir(HTIRS2);      //read IR seeker value
				if (_dirAC > 5)
				{
					//dump block
					motor[rdrive] = 0;
					motor[ldrive] = 0;
					wait10Msec(30000);
					//straight(100,100, 5);  //change the 5 to whatever distance fit the situation
					//GyroLeft(45, 100000000);
					//straight(100, 100, 39);
					//GyroRight(47, 10000000);
					//MBD(42, 100, 1000000);
				}
				else
				{
					//dump block
					//straight(100,100, 5);  //change the 5 to whatever distance fit the situation
	        //GyroLeft(45, 100000000);
	        //straight(100, 100, 39);
	        //GyroRight(47, 10000000);
	        //MBD(42, 100, 1000000);
				}
			}
		}
	}
}

	//straight(100,100, 5);  //change the 5 to whatever distance fit the situation
	//GyroLeft(45, 100000000);
	//straight(100, 100, 39);
	//GyroRight(47, 10000000);
	//MBD(42, 100, 1000000);
